# Model arguments
model_revision: main
torch_dtype: float32
attn_implementation: eager
bf16: false
tf32: false

# Dataset arguments
dataset_id_or_path: 'openai/gsm8k'

# Training arguments
max_steps: 20 # Original 450
gradient_accumulation_steps: 2
gradient_checkpointing: false
gradient_checkpointing_kwargs:
use_reentrant: false
learning_rate: 3.0e-6 # 1.0e-6 1.0e-6 as in the deepseek math paper 5-e7 from https://hijkzzz.notion.site/unraveling-rlhf-and-its-variants-engineering-insights#147d9a33ecc9806090f3d5c749d31f05
lr_scheduler_type: cosine
warmup_ratio: 0.03

# GRPO arguments
use_vllm: false
num_generations: 2
per_device_train_batch_size: 2
beta: 0.01 # 0.04 as in the deepseek math paper 0.001 from https://hijkzzz.notion.site/unraveling-rlhf-and-its-variants-engineering-insights#147d9a33ecc9806090f3d5c749d31f05
max_prompt_length: 64
max_completion_length: 256

# CPU-specific optimizations
num_workers: 36  # = Number of physical cores (18 cores/CPU x 2 CPUs)
ddp_enabled: true
torch_distributed_backend: "gloo"  # Required when using CPU
torch_num_threads: 72  # Total threads (36 threads/CPU x 2 CPUs)
torch_intraop_threads: 36  # Each operation uses 1 CPU (36 threads)
torch_interop_threads: 2  # Keep this to avoid contention
pin_memory: false  # Not needed for CPU
non_blocking: false  # Only meaningful with GPU
prefetch_factor: 4  # Speed up data reading
torch_use_deterministic_algorithms: false  # Disable to speed up
torch_use_cpu_affinity: true  # Pin threads to physical cores

# IMPORTANT: NUMA-aware settings (Linux)
numactl_enabled: true           # Required to use both CPUs evenly
numactl_cpunodebind: "0,1"      # Bind process to both CPUs
torch_use_cpu_affinity: true    # Pin threads to physical cores
 
numactl_enabled: true         
numactl_cpunodebind: "0,1"     
torch_use_cpu_affinity: true   

# Logging arguments
logging_strategy: steps
logging_steps: 2
report_to:
- tensorboard
save_strategy: "steps"
save_steps: 25
seed: 42

# Script arguments
max_rounds: 10000

# Model-specific arguments
model_name_or_path: unsloth/Qwen2.5-0.5B-Instruct
output_dir: runs/gsm8k/multinode/Qwen2.5-0.5B-Instruct-Gensyn-Swarm
